### ISSUE TITLE
d.ts definition is not available

### ISSUE THREAD

**Issue by badicuady** [tastypackets/node-ad-tools#19]
Please add the node-ad-tools.d.ts for all of us Typescript lovers. Please find the definition attached.

[node-ad-tools.d.ts.txt](https://github.com/tastypackets/node-ad-tools/files/4344504/node-ad-tools.d.ts.txt)

**Comment by badicuady** [comment]
Improved version...
[node-ad-tools.d.ts.txt](https://github.com/tastypackets/node-ad-tools/files/4344978/node-ad-tools.d.ts.txt)

**Comment by tastypackets** [comment]
This looks great! I’ll try and remeber to test and add it this week!
